// App database — 3 real apps from health_app_privacy_analysis.json + 2 dummy fillers
window.APPS_DB = [
  {
    id: "strava",
    name: "Strava",
    tagline: "Run, Bike, Swim",
    category: "Health & Fitness",
    developer: "Strava Inc.",
    rating: 4.7,
    reviews: "283K",
    size: "162 MB",
    age: "4+",
    iconBg: "#FC4C02",
    iconGlyph: "S",
    screenshots: ["route", "leaderboard", "segments"],
    description:
      "Track and share your workouts with the global Strava community. Get motivated by friends, compete on segments, and analyze every kilometre of your run or ride.",
    grade: "D",
    gradeColor: "#f57c00",
    gradeLabel: "POOR",
    collects: [
      "Precise GPS routes (every activity)",
      "Heart rate & cadence from connected devices",
      "Sleep data",
      "Phone contacts",
      "Photos & live location",
      "Device identifiers & IP address",
    ],
    shares: [
      { text: "Activities public by default — indexed by search engines", type: "bad" },
      { text: "Third-party partners never named in policy", type: "bad" },
      { text: "Deidentified GPS data commercially licensed via Strava Metro", type: "bad" },
      { text: "AI training on health & location data", type: "bad" },
      { text: "Personal data not sold (deidentified data only)", type: "neutral" },
      { text: "Opt-out controls exist for advertising", type: "good" },
    ],
    sentence:
      "Activities and GPS routes are public by default. Third-party partners are never named, and deidentified movement data is commercially licensed without opt-out.",
    dimensions: {
      collection:   { grade: "E", score: 20, note: "9 data types incl. precise GPS, heart rate, sleep & phone contacts" },
      sharing:      { grade: "D", score: 40, note: "Partners never named; GPS data licensed commercially to governments" },
      control:      { grade: "D", score: 44, note: "45-day deletion delay; no opt-out from Heatmap or Metro licensing" },
      transparency: { grade: "D", score: 40, note: "Policy may change without notice; 'material' changes undefined" },
      storage:      { grade: "D", score: 42, note: "US-based primary servers; EU data via Irish subsidiary" },
    },
    keyFindings: [
      { severity: "high",   title: "Public by default",                      detail: "Your routes, times, and home neighbourhood are visible to anyone online until you go digging through the settings to lock it down." },
      { severity: "high",   title: "Zero named partners",                    detail: "Strava admits it shares your data with other companies but won't name a single one, so you have no idea who actually ends up with your GPS history." },
      { severity: "high",   title: "Global Heatmap still active",            detail: "Your runs still feed a public worldwide heatmap that once accidentally exposed secret military bases, and Strava hasn't changed a thing about it since." },
      { severity: "high",   title: "AI training on personal data",           detail: "Strava uses your location history and heart rate to train its AI, and the option to stop it is buried where most people will never look." },
      { severity: "medium", title: "Acquisition clause — no health data carve-out", detail: "If Strava gets bought, every route and heartbeat they have on you goes straight to the new owner with no restrictions and no say for you." },
      { severity: "medium", title: "Contacts synced on an ongoing basis",    detail: "If you once let Strava see your contacts, it quietly keeps re-reading that list in the background on a regular basis." },
      { severity: "medium", title: "Consent withdrawal not retroactive",     detail: "Updating your privacy settings today won't delete what they already collected, so all your past routes and health data stay in their system." },
    ],
  },
  {
    id: "flo",
    name: "Flo",
    tagline: "Period & Health Tracker",
    category: "Health & Fitness",
    developer: "Flo Health Inc.",
    rating: 4.8,
    reviews: "587K",
    size: "258 MB",
    age: "12+",
    iconBg: "#8B1A9B",
    iconGlyph: "F",
    screenshots: ["calendar", "insights", "symptoms"],
    description:
      "Track your period, ovulation and reproductive health. Log symptoms, mood and medications. Get AI-powered cycle predictions and personalised health insights.",
    grade: "C",
    gradeColor: "#fbc02d",
    gradeLabel: "MODERATE",
    collects: [
      "Menstrual cycle dates and patterns",
      "Pregnancy status and history",
      "Sexual activity & contraception use",
      "Mood & mental health symptoms",
      "Weight, BMI & sleep patterns",
      "Device identifiers & IP address",
    ],
    shares: [
      { text: "Shared with TikTok, Meta, Pinterest, Google Ads via AppsFlyer", type: "bad" },
      { text: "One AppsFlyer share is mandatory and cannot be refused", type: "bad" },
      { text: "FTC-settled for sharing health data after promising not to (2021)", type: "bad" },
      { text: "All advertising partners are named", type: "good" },
      { text: "Personal data not sold or rented for money", type: "good" },
      { text: "Anonymous Mode unlinks identity from health data", type: "good" },
    ],
    sentence:
      "Fined by the FTC for sharing health data after promising not to. One mandatory AppsFlyer share cannot be refused. Chain sharing reaches TikTok, Meta and Pinterest.",
    dimensions: {
      collection:   { grade: "D", score: 49, note: "Reproductive health, pregnancy, sexual activity, mood, mental health" },
      sharing:      { grade: "C", score: 55, note: "TikTok, Meta, Pinterest via AppsFlyer chain — no guaranteed endpoint" },
      control:      { grade: "D", score: 49, note: "One mandatory share cannot be refused; 90-day backup deletion window" },
      transparency: { grade: "B", score: 80, note: "Annual policy review; advance email notice for material changes" },
      storage:      { grade: "B", score: 75, note: "ISO 27001 & 27701 certified; UK-based (GDPR home jurisdiction)" },
    },
    keyFindings: [
      { severity: "high",   title: "TikTok Ad Manager connection",              detail: "Your subscription status and device ID get sent to TikTok, which can match it to your TikTok profile and likely figure out you're tracking a pregnancy or fertility issue." },
      { severity: "high",   title: "Mandatory data share — cannot be refused",  detail: "One data transfer to AppsFlyer happens at sign-up and cannot be blocked no matter what privacy settings you pick." },
      { severity: "high",   title: "Chain sharing through AppsFlyer",           detail: "From AppsFlyer your data gets passed along to TikTok, Pinterest, Meta and Google Ads, and Flo has no control over what any of them do with it after that." },
      { severity: "high",   title: "FTC settlement — proven misuse",            detail: "Flo promised never to share your health data, then shared menstrual cycle and pregnancy information with Facebook and Google for ad targeting and got caught and fined for it." },
      { severity: "medium", title: "Gender inferred from usage",                detail: "Flo works out your sex or gender just from how you use the app and stores that guess in your profile, even if you never said anything." },
      { severity: "medium", title: "Third-party data enrichment",               detail: "Flo may be receiving extra information about you from companies you've never heard of to fill in gaps in your profile without telling you." },
    ],
  },
  {
    id: "yuka",
    name: "Yuka",
    tagline: "Food & Cosmetic Scanner",
    category: "Health & Fitness",
    developer: "Yuca SAS",
    rating: 4.7,
    reviews: "891K",
    size: "88 MB",
    age: "4+",
    iconBg: "#4CAF50",
    iconGlyph: "Y",
    screenshots: ["scan", "score", "alternatives"],
    description:
      "Scan food and cosmetic products to instantly see their health impact. Find healthier alternatives and understand what's really in what you eat and apply.",
    grade: "B",
    gradeColor: "#7cb342",
    gradeLabel: "GOOD",
    collects: [
      "Product scan history (barcodes scanned)",
      "Search queries within the app",
      "Device identifiers & IP address",
      "Approximate location",
      "Email address (if registered)",
      "Email signature content (if call-out feature used)",
    ],
    shares: [
      { text: "Every food scan processed by OpenAI — no opt-out", type: "bad" },
      { text: "Google Analytics Demographics profiling enabled", type: "bad" },
      { text: "All 8 service providers named by name", type: "good" },
      { text: "No advertising — subscription model only", type: "good" },
      { text: "GDPR-native French jurisdiction for all users", type: "good" },
      { text: "No data sold or rented", type: "good" },
    ],
    sentence:
      "The most transparent of the three: subscription-only, all vendors named, no advertising. Every food scan passes through OpenAI with no opt-out — the central irony of an app about hidden ingredients.",
    dimensions: {
      collection:   { grade: "C", score: 59, note: "Scan patterns reveal diabetes, allergies, pregnancy — legally 'not sensitive'" },
      sharing:      { grade: "C", score: 69, note: "All 8 vendors named; subscription model; no advertising relationships" },
      control:      { grade: "B", score: 80, note: "GDPR-native French jurisdiction; clean regulatory history; all vendors named" },
      transparency: { grade: "B", score: 80, note: "Every provider named with stated purpose; independently auditable policy" },
      storage:      { grade: "B", score: 75, note: "European infrastructure; GDPR as home law; no incident history" },
    },
    keyFindings: [
      { severity: "high",   title: "OpenAI processes every food scan",                    detail: "Every barcode you scan gets sent to OpenAI, and Yuka doesn't say how long it keeps your scans or whether they could end up training a future AI model." },
      { severity: "high",   title: "Call-out feature shifts legal liability to users",    detail: "If you email a food brand through Yuka and the brand decides to take legal action over your message, it's you personally who would face that, not Yuka." },
      { severity: "high",   title: "Yuka receives your email signature via call-out CC",  detail: "When you contact a brand through Yuka, the app copies itself into the email so it can read your message, your address, and your email signature with your name, job and phone number." },
      { severity: "high",   title: "Scan data reveals health conditions — legally 'not sensitive'", detail: "Scanning gluten-free, diabetic-safe or pregnancy products regularly paints a pretty clear picture of your health, even though Yuka officially calls none of that sensitive data." },
      { severity: "medium", title: "Google Analytics Demographics & Interests enabled",    detail: "Yuka sends your usage to Google with advertising features switched on, so Google can build a profile of your age, interests and income that then flows across its ad network." },
      { severity: "medium", title: "Facebook login links identity to Meta",                detail: "If you signed up with Facebook, Meta now knows you use Yuka and can attach that to your advertising profile along with whatever your scans reveal about your diet and health." },
      { severity: "medium", title: "No response to Do Not Track signals",                 detail: "Even if you've turned on Do Not Track in your device settings, Yuka explicitly ignores it and has put that in writing in their privacy policy." },
    ],
  },
  {
    id: "vivo",
    name: "Vivo Habit",
    tagline: "Habits & Daily Goals",
    category: "Health & Fitness",
    developer: "Vivo Labs GmbH",
    rating: 4.8,
    reviews: "124K",
    size: "58 MB",
    age: "4+",
    iconBg: "#2E7D6B",
    iconGlyph: "V",
    screenshots: ["habits", "streak", "insights"],
    description:
      "Build lasting habits with a simple, private tracker. No account required. Everything stays on your device. No ads, no tracking, no data sharing.",
    grade: "A",
    gradeColor: "#2e7d32",
    gradeLabel: "EXCELLENT",
    collects: [
      "Daily habit completions (stored locally)",
      "Mood check-ins (optional, local only)",
    ],
    shares: [
      { text: "Nothing shared with any third parties", type: "good" },
      { text: "All data stored on device only", type: "good" },
      { text: "Instant deletion — no account needed", type: "good" },
      { text: "iCloud backup optional and user-controlled", type: "neutral" },
    ],
    sentence:
      "Minimal collection, nothing shared. Your habit data stays on your device. No account, no tracking, no third-party connections.",
    dimensions: {
      collection:   { grade: "A", score: 92, note: "Only logs what you manually enter; stored entirely on-device" },
      sharing:      { grade: "A", score: 98, note: "No third-party SDK or network connection of any kind" },
      control:      { grade: "A", score: 96, note: "Delete anything instantly; no account or login required" },
      transparency: { grade: "A", score: 94, note: "One-page plain-English policy; full source code auditable" },
      storage:      { grade: "A", score: 100, note: "On-device only; iCloud optional and encrypted end-to-end" },
    },
    keyFindings: [
      { severity: "medium", title: "iCloud sync is optional",        detail: "If iCloud backup is enabled in iOS settings, habit data is backed up under Apple's privacy policies. Users can disable this at any time." },
      { severity: "positive", title: "No network connections",       detail: "The app makes zero outbound network calls during normal use. Verified by independent network traffic analysis." },
      { severity: "positive", title: "No account required",          detail: "No sign-up, no email, no identity. Your habits are yours alone." },
    ],
  },
  {
    id: "sleepcast",
    name: "SleepCast",
    tagline: "Sleep Sounds & Tracker",
    category: "Health & Fitness",
    developer: "SleepCast Ltd.",
    rating: 4.6,
    reviews: "203K",
    size: "112 MB",
    age: "4+",
    iconBg: "#3949AB",
    iconGlyph: "Z",
    screenshots: ["sounds", "sleep-score", "trends"],
    description:
      "Fall asleep faster with curated soundscapes, sleep meditations, and light sleep tracking. Understand your patterns and wake refreshed.",
    grade: "B",
    gradeColor: "#7cb342",
    gradeLabel: "GOOD",
    collects: [
      "Sleep session duration & quality scores",
      "Sound preferences",
      "Device motion data (sleep detection)",
      "Account email (if registered)",
    ],
    shares: [
      { text: "Sleep data not sold to third parties", type: "good" },
      { text: "Analytics shared with Firebase (Google)", type: "neutral" },
      { text: "No advertising network connections", type: "good" },
      { text: "Deletion processed within 30 days", type: "neutral" },
    ],
    sentence:
      "Good defaults and no advertising model. Sleep data stays internal. Firebase analytics is the main third-party connection.",
    dimensions: {
      collection:   { grade: "B", score: 72, note: "Session duration, motion data and sound preferences only" },
      sharing:      { grade: "B", score: 78, note: "Firebase analytics only; no advertising or data broker connections" },
      control:      { grade: "B", score: 76, note: "Account deletion within 30 days; full opt-out from analytics" },
      transparency: { grade: "B", score: 82, note: "Clear policy with named providers; annual review cycle" },
      storage:      { grade: "B", score: 80, note: "EU servers for EU users; encrypted in transit and at rest" },
    },
    keyFindings: [
      { severity: "medium", title: "Firebase analytics always on",      detail: "Google Firebase analytics is active by default with no in-app opt-out. Users must contact support to disable. This sends usage patterns to Google's infrastructure." },
      { severity: "medium", title: "Motion data used for sleep detection", detail: "The app uses device accelerometer and gyroscope continuously during sleep sessions. This data is processed on-device but session summaries are synced to the cloud." },
      { severity: "positive", title: "No advertising model",             detail: "Revenue is subscription-only. No advertising SDKs, no data broker relationships, no brand partnerships." },
      { severity: "positive", title: "EU server residency",              detail: "All EU user data is stored on EU-based servers and is subject to GDPR as a compliance obligation." },
    ],
  },
];
